view:
  forward-to-frontend-url: forward:/index.html
  frontend-managed-urls:
    /,
    /home,
    /user,
    /user/**,
    /categories,
    /operations,
    /budgets

logging.level:
  ROOT: info

spring.jackson.serialization.indent_output: true

spring.security:
  user.name: user
  user.password: 12345

application:
  security:
    permit:
      /, /home, /user/login,

      /api/user/authenticated, /test,

      /actuator/**,

      /configuration/ui, /configuration/security,

      /v2/api-docs, /swagger-resources/**, /swagger-ui.html, /webjars/**"

    resources:
      /**/*.js, /**/*.css,
      /**/*.ico, /**/*.img, /**/*.png