view:
  forward-to-frontend-url: forward:/index.html
  frontend-managed-urls:
    /,
    /home,
    /user,
    /user/**,
    /categories,
    /operations,
    /budgets

logging.level:
  ROOT: info

spring.jackson.serialization.indent_output: true

spring.security:
  user.name: user
  user.password: 12345

application:
  security:
    permit:
      /, /home, /user/login,

      /api/user/register, /api/user/authenticated, /test,

      /actuator/**,

      /configuration/ui, /configuration/security,

      /v2/api-docs, /swagger-**, /webjars/**"

    resources:
      /**/*.js, /**/*.css,
      /**/*.ico, /**/*.img, /**/*.png

spring:
  datasource:
    url: jdbc:h2:file:./database/application;AUTO_SERVER=TRUE;

  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        show_sql: true