view:
  forward-to-frontend-url: forward:/index.html
  frontend-managed-urls:
    /,
    /user,
    /user/**,
    /categories

logging.level:
  ROOT: info

spring.jackson.serialization.indent_output: true

spring.security:
  user.name: user
  user.password: 12345

application:
  security:
    permit:
      /,
      /api/user/authenticated, /test,

      /actuator/**,

      /v2/api-docs, /configuration/ui, /swagger-resources, /configuration/security, /swagger-ui.html, /webjars/**"

    resources:
      /**/*.js, /**/*.css,
      /**/*.ico, /**/*.img, /**/*.png